### ISSUE TITLE
フロントエンドのロジックをバックエンドに寄せたい

### ISSUE THREAD

**Issue by subaru-hello** [subaru-hello/Zeroken#119]
# 概要
下記処理をバックエンドに移す

- app/frontend/pages/Analyze.vue

https://github.com/subaru-hello/Zeroken/blob/005a8b0ac8860707f9aa0f0312e204eb084feede/app/frontend/pages/Analyze.vue#L336

## 詳細
現状、診断ロジックを全てフロントに任せてしまっている。本来、フロントはデータの「表示」という責務、バックはデータの「保存・加工」という責務を持っている。そのため、現状のままだと、フロントの動きが重くなる可能性がある。だから、Analyze.vueに書いた診断ロジックをフロントからバックに移植させていきたい。
### フロントからpostする値
- [x] #126 
- [x] 体重（TastAnswers#create）
- [x] １軒目での気分（TastAnswers#create）
### バックで作成する値
- [x] #128
- [x] #122 
- [x] #123
- [x] #125
- [x] #124  

## TODO
- [x] 不要なテーブルをドロップ(MyShuchedules,AlcoholAnalyzes,Relationships)
- [x] 必要なテーブルの作成(AnalyzeResults,Questions,Answers,Descriptions,Alcohols)
- [x] コントローラーにapiを作成(AnalyzeResults,Questions,Answers,Descriptions,Alcohols)
- [x] 診断ロジックをコントローラーに移す

### 不要なテーブルをドロップ(MyShuchedules,AlcoholAnalyzes,Relationships)
テーブル設計の見直しに伴い、不要なテーブルを削除する

### 必要なテーブルの作成

**AnalyzeResults**
診断結果を保存するテーブル

- alcohol_strongness(お酒の強さ) integer(enum)
お酒の強さを数字で持たせる
concernsにsumResultを用意する。 
sumResult > 3 ? 4 : sumResult > 0 ? 3 : sumResult === 0 ? 2 : sumResult > -3 ? 1 : 0; //4: 酒豪, 3: やや酒豪, 2: 普通, 1: やや下戸, 0: 下戸
- next_motivation(一軒目の気分) integer(enum)
一軒目の気分を数字で持たせる

- total_alcohol_amounts
yourWeight(paramsで受け取る保存はしない。) * coefficient(AnalyzeResults class内に定義する) * AlcoholInVein/percentage

- alcohol_first
一杯目を持たせる
- alcohol_second
2杯目を持たせる
- alcohol_third
3杯目を持たせる

- alcohol_forth
4杯目を持たせる

**Questions**
質問内容を保存するテーブル

- title
質問内容
- not_answered
- 未回答項目

**Answers**
- question_id
質問と紐づける

- choice enum
回答項目を記入する(いつも、時々、全くない)
- point
項目ごとの値(1を選択したら10、２を選択したら-0.1などを返すようになる。)

**Descriptions**
診断結果の説明を書く

- explanation
「〇〇な下戸、〇〇な酒豪」というような表現が入る。

**Alcohols**
- id
- name
- alcohol_percentage
- alcohol_amountt
- description

**Favorites**
- user_id
- alcohol_id

**AlcoholInVein**
アルコール体内血中濃度を保存するテーブル
- percentage
idが1~16まであり、それぞれがアルコール体内血中濃度を保存している。

下記公式を作成するために、0.04を保存する。
```
   let AlcoholStrongness =
        sumResult > 3 ? 4 : sumResult > 0 ? 3 : sumResult === 0 ? 2 : sumResult > -3 ? 1 : 0; //4: 酒豪, 3: やや酒豪, 2: 普通, 1: やや下戸, 0: 下戸
      let Nomivation = this.nextMotivation; //flesh: 0, tipsy: 1, heavy_drunk: 2
      let alcoholInVein =
        AlcoholStrongness === 4 && Nomivation === 0
          ? 0.04
```
AnalyzeResultsがこの数値を引っ張り、concernsにあるsumPointsとnext_motivation、alcohol_strongnessを組み合わ背、最終的に下記式が出来上がる。
```
  let coefficient = 833;
      let yourWeight = this.weight;
      let totalAlcoholAmount = yourWeight * coefficient * alcoholInVein;
```

## ER図
**変更前**
<a href="https://gyazo.com/9ecf7f7bcfe55dbb9bf87eeaf1682c2b"><img src="https://i.gyazo.com/9ecf7f7bcfe55dbb9bf87eeaf1682c2b.png" alt="Image from Gyazo" width="723"/></a>

**変更後**
<a href="https://gyazo.com/01cb3a0b00080403894db80939e580af"><img src="https://i.gyazo.com/01cb3a0b00080403894db80939e580af.png" alt="Image from Gyazo" width="719"/></a>

### コントローラーにapiを作成(AnalyzeResults,Questions,Answers,Descriptions,Alcohols)
postmanでjsonのレスポンス、リクエストの反応を確認する。

### 診断ロジックをコントローラーに移す
下記の処理を全てコントローラで行うようにする。できるかな、、
1. app/frontend/pages/Analyze.vue
https://github.com/subaru-hello/Zeroken/blob/005a8b0ac8860707f9aa0f0312e204eb084feede/app/frontend/pages/Analyze.vue#L336

**Comment by subaru-hello** [comment]
診断フロー

- [ ] 質問13項目(Questions)それぞれ三つの選択肢(Answers)から一つの回答(Answers)を選ぶ。
- [ ] 体重(AnalyzeResultls)を選択する
- [ ] 一軒目でなりたい状態(AnalyzeResultls)を選択する

## 1. Answer13個を配列に入れる
answersテーブルにデータを39個持たせておく（1: -10.00, 2: 0.02, 3: 0.50など）ユーザーがクリックした値が[1,4,8,10]のようにparamsに入り、postでAnswerに送られる。
## 2. Concernsに記述したtotalPointsメソッドが実行される

**Comment by subaru-hello** [comment]
リクエスト、レスポンスの流れ。
１post Answer･choice(13個) →create
2 get Answer.find(params[:id]).point, 
3 concerns sumPoints Answer.find(params[:id]).point.all
3 concerns alcoholStrongness if sumPoints >0 酒豪 elsif sumPoints < 0 下戸　else 普通
4   let alcoholInVein =
        AlcoholStrongness === 4 && Nomivation === 0
          ? 0.04
  let coefficient = 833;
      let yourWeight = this.weight;
      let totalAlcoholAmount = yourWeight * coefficient * alcoholInVein;

4 get

**Comment by subaru-hello** [comment]
- [ ] フロントで作成したtast_answersは、TastAnswerテーブルへ保存、weight,next_motivationはAnalyzeResultへ保存
- [ ] AnalyzeResultで、現在のユーザーが作成した最新のTastResultを呼び、pluckで値だけ取得する。その後、alcohol_strongness,total_alcohol_amountを作成する。
- [ ] AnalyzeResultテーブルのカラムは、next_motivation,total_alcohol_amount,alcohol_strongness,descriptionの4つに変更
- [ ] Alcoholモデルにalcohol_amountカラムを追加。alcohol_amountにはalcohol_percentageとamount_per_glass(一杯あたりの量)を掛け合わせたものを記載する。
- [ ] Alcohol#indexでは、現在のユーザーが作成した最新のAnalyzeResultを呼び、そこにあるtotal_alcohol_amountカラムをもとに配列内へお酒をpushする
- [ ] view側でAlcohol#indexをgetし、表示させる

**Comment by subaru-hello** [comment]
#129 に引き継ぎ
